
-- THERE ARE TOW WAYS TO ENABLE DAC (DEDICATED ADMINISTRATOR CONNECTION )
-- 1. GRAPHICAL THROUGH 2. SCRIPT THROUGH

-- OBJECT EXPLORER --> RIGHT CLICK ON INSTANANCE --> FACETS --> NEW WINDOW WILL BE POPUP --> 
--> FACETS --> Surface area configuration --> REMOTE DAC ENABLED --> TRUE FOR ENABLE FALSE FOR DESABLE


--  FIRST CHECK DAC CONNECTION IS ENABLED OR NOT 

SP_CONFIGURE

--ENABLED DAC CONNECTION
SP_CONFIGURE'remote admin connections',1
GO
RECONFIGURE
GO 

SP_CONFIGURE
